apiVersion: v1
kind: Pod
metadata:
  name: kapplet
  labels:
    instance: kapplet
spec:
  containers:
    - name: kapplet
      image: localhost:32000/kappa:latest
      ports:
        - containerPort: 7701
          name: ktor
      volumeMounts:
        - name: kapplet
          mountPath: /opt/.kappa
          readOnly: false
  volumes:
    - name: kapplet
      hostPath:
        path: "/home/super/var/kapplet"
  restartPolicy: Never
  terminationGracePeriodSeconds: 300

---

apiVersion: v1
kind: Service
metadata:
  name: kapplet
spec:
  selector:
    instance: kapplet
  ports:
    - port: 7701
      nodePort: 30701
      name: ktor
  type: NodePort
