apiVersion: v1
kind: Pod
metadata:
  name: kapplet
  labels:
    instance: kapplet
spec:
  hostAliases:
    - ip: 192.168.0.19
      hostnames:
        - "nevada"
        - "artifactory"
  containers:
    - name: kapplet
      image: localhost:32000/kappa:latest
      env:
        - name: M2_HOME
          value: "/opt/3.5.4"
      ports:
        - containerPort: 7701
          name: ktor
      volumeMounts:
        - name: kapplet
          mountPath: /opt/.kappa
          readOnly: false
        - name: m2
          mountPath: /opt/m2
          readOnly: false
  volumes:
    - name: kapplet
      hostPath:
        path: "/home/super/var/kapplet/.kappa"
    - name: m2
      hostPath:
        path: "/home/super/var/shared/m2"
  restartPolicy: Never
  terminationGracePeriodSeconds: 300

---

apiVersion: v1
kind: Service
metadata:
  name: kapplet
spec:
  selector:
    instance: kapplet
  ports:
    - port: 7701
      nodePort: 30701
      name: ktor
  type: NodePort
