
atomix:
  profile: ${ATOMIX_PROFILE}
  bootstrap: ${ATOMIX_BOOTSTRAP}
  node:
    id: ${ATOMIX_NODE_ID}
    host: ${ATOMIX_NODE_HOST}
    port: ${ATOMIX_NODE_PORT}
    data-dir: .

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 3m

kappa:
  default:
    host: localhost:7701
  server:
    port: 7700

kapplet:
  server:
    port: ${KAPPLET_SERVER_PORT}
  web:
    port: ${KAPPLET_WEB_PORT}
  deployerEnabled: true
  cacheLocation: .kappa/cache
