#
# Single node cluster
#
atomix:
  profile: Consensus
  bootstrap: A:localhost:5001;B:localhost:5002;C:localhost:5003
  node:
    id: B
    host: localhost
    port: 5002
    data-dir: .

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 3m

kappa:
  default:
    host: localhost:7701
  server:
    port: 7700

kapplet:
  server:
    port: 7721
  web:
    port: 7723
  deployerEnabled: true
  cacheLocation: .kappa/cache
